const vinylsList = 
    [
        {imagePath: 'images/1.png', id:2, titleGR: 'ΤΑ ΧΡΥΣΑ ΧΕΡΙΑ', title2: 'ΧΡΗΣΤΑΚΗΣ', title3: '', musicPath: 'music/1.mp3'},
        {imagePath: 'images/2.png', id:3, titleGR: 'ΑΕΚΑΡΑ', title2: 'ΧΡΗΣΤΑΚΗΣ', title3: '', musicPath: 'music/2.mp3'},
        {imagePath: 'images/3.png', id:4, titleGR: 'ΥΜΝΟΣ ΤΗΣ Α.Ε.Κ', title2: '(Μπασκετ)', title3: 'ΜΑΡΙΝΟΣ ΒΟΜΒΑΣ', title2: '', title3: '', musicPath: 'music/3.mp3'},
        {imagePath: 'images/4.png', id:4, titleGR: 'ΥΜΝΟΣ ΤΗΣ Α.Ε.Κ', title2: '(ποδόσφαιρο)', title3: 'ΜΑΡΙΝΟΣ ΒΟΜΒΑΣ', musicPath: 'music/4.mp3'},
        {imagePath: 'images/5.png', id:5, titleGR: 'Α.Ε.Κ', title2: ' (Έμβατήριον)', title3: 'ΓΙΩΡΓΟΣ ΚΑΣΣΙΑΝΟΣ', musicPath: 'music/5.mp3'},
        {imagePath: 'images/6.png', id:7, titleGR: 'Α.Ε.Κ - ΤΡΥΠΙΑΣ', title2: '', title3: '', musicPath: 'music/6.mp3'},
        {imagePath: 'images/7.png', id:7, titleGR: 'Α.Ε.Κ', title2: '', title3: '', musicPath: 'music/7.mp3'},
        {imagePath: 'images/8.png', id:7, titleGR: 'ΑΕΚΑΡΑ 1968', title2: '', title3: '', musicPath: 'music/8.mp3'},
        {imagePath: 'images/9.png', id:7, titleGR: 'Α.Ε.Κ ΜΙΜΗΣ', title2: '', title3: '', musicPath: 'music/9.mp3'},
        {imagePath: 'images/10.png', id:7, titleGR: 'Α.Ε.Κ ΣΤΑΘΗΣ', title2: '', title3: '', musicPath: 'music/10.mp3'},
        {imagePath: 'images/11.png', id:7, titleGR: 'ΥΜΝΟΣ ΣΤΗΝ ΑΕΚ', title2: '', title3: '', musicPath: 'music/11.mp3'},
        {imagePath: 'images/12.png', id:7, titleGR: 'Α.Ε.Κ ΠΕΤΡΙΔΗΣ', title2: '', title3: '', musicPath: 'music/12.mp3'},
        {imagePath: 'images/13.png', id:7, titleGR: 'ΥΜΝΟΣ ΣΤΗΝ ΑΕΚ', title2: 'ΠΑΛΑΙΟΛΟΓΟΣ', title3: '', musicPath: 'music/13.mp3'},
        {imagePath: 'images/14.png', id:7, titleGR: 'Ο ΥΜΝΟΣ ΤΗΣ ΑΕΚ', title2: '', title3: '', musicPath: 'music/14.mp3'},
        {imagePath: 'images/15.png', id:7, titleGR: 'ΟΤΑΝ ΦΟΡΑΣ ΤΑ ΚΙΤΡΙΝΑ', title2: '', title3: '', musicPath: 'music/15.mp3'},
        {imagePath: 'images/16.png', id:7, titleGR: 'ΥΜΝΟΣ ΤΗΣ ΑΕΚ', title2: 'ΨΙΛΟΠΟΥΛΟΣ', title3: '', musicPath: 'music/16.mp3'},
        {imagePath: 'images/17.png', id:7, titleGR: 'ΦΙΛΑΔΕΛΦΙΩΤΙΣΣΑ', title2: '', title3: '', musicPath: 'music/17.mp3'},
        {imagePath: 'images/18.png', id:7, titleGR: 'ΑΕΚ ΣΚΛΑΒΙΑ', title2: '', title3: '', musicPath: 'music/18.mp3'},
        {imagePath: 'images/19.png', id:7, titleGR: 'Α.Ε.Κ', title2: 'ΑΓΡΙΑΝΙΤΗΣ', title3: '', musicPath: 'music/19.mp3'},
        {imagePath: 'images/20.png', id:7, titleGR: 'Α.Ε.Κ', title2: 'Μυτίκα', title3: '', musicPath: 'music/20.mp3'},
        {imagePath: 'images/21.png', id:7, titleGR: 'Α.Ε.Κ', title2: 'Μυτίκα', title3: '', musicPath: 'music/21.mp3'},
        {imagePath: 'images/22.png', id:7, titleGR: 'Α.Ε.Κ', title2: 'Μυτίκα', title3: '', musicPath: 'music/22.mp3'},
        {imagePath: 'images/23.png', id:7, titleGR: 'Α.Ε.Κ', title2: 'Μυτίκα', title3: '', musicPath: 'music/23.mp3'},
        {imagePath: 'images/24.png', id:7, titleGR: 'Α.Ε.Κ', title2: 'Μυτίκα', title3: '', musicPath: 'music/24.mp3'},
        {imagePath: 'images/25.png', id:7, titleGR: 'Α.Ε.Κ', title2: 'Μυτίκα', title3: '', musicPath: 'music/25.mp3'},
        {imagePath: 'images/26.png', id:7, titleGR: 'Α.Ε.Κ', title2: 'Μυτίκα', title3: '', musicPath: 'music/26.mp3'},
    ];

export {vinylsList}