
    const vinylsList = 
    [
        {imagePath: 'images/1.png', id:2, titleGR: 'Α.Ε.Κ.', title2: 'ΜΙΜΗΣ ΠΑΠΑΪΩΑΝΝΟΥ', title3: '', musicPath: 'music/1.mp3'},
        {imagePath: 'images/2.png', id:3, titleGR: 'ΥΜΝΟΣ ΤΗΣ Α.Ε.Κ.', title2: '(Ποδόσφαιρο)', title3: 'ΜΑΡΙΝΟΣ ΒΟΜΒΑΣ', musicPath: 'music/2.mp3'},
        {imagePath: 'images/3.png', id:4, titleGR: 'ΥΜΝΟΣ ΤΗΣ Α.Ε.Κ.', title2: '(Μπάσκετ)', title3: 'ΜΑΡΙΝΟΣ ΒΟΜΒΑΣ', title2: '', title3: '', musicPath: 'music/3.mp3'},
        {imagePath: 'images/4.png', id:4, titleGR: 'Ο ΥΜΝΟΣ ΤΗΣ Α.Ε.Κ', title2: 'ΧΩΡΩΔΙΑ ΕΛΛΗΝΩΝ ΚΑΛΛΙΤΕΧΝΩΝ', title3:'', musicPath: 'music/4.mp3'},
        {imagePath: 'images/5.png', id:5, titleGR: 'ΑΕΚΑΡΑ', title2: 'ΧΡΗΣΤΑΚΗΣ', title3:'', musicPath: 'music/5.mp3'},
        {imagePath: 'images/6.png', id:7, titleGR: 'ΤΑ ΧΡΥΣΑ ΧΕΡΙΑ', title2: 'ΧΡΗΣΤΑΚΗΣ', title3: '', musicPath: 'music/6.mp3'},
        {imagePath: 'images/7.png', id:7, titleGR: 'Α.Ε.Κ. - ΤΡΥΠΙΑΣ', title2: 'ΤΡΙΟ ΑΜΟΡΕ', title3: '', musicPath: 'music/7.mp3'},
        {imagePath: 'images/8.png', id:7, titleGR: 'Α.Ε.Κ.', title2: 'ΓΙΩΡΓΟΣ ΠΕΤΡΙΔΗΣ', title3: '', musicPath: 'music/8.mp3'},
        {imagePath: 'images/9.png', id:7, titleGR: 'ΑΕΚΑΡΑ 1968', title2: 'ΘΕΟΔΩΡΟΣ ΑΓΡΙΝΙΩΤΗΣ', title3: '', musicPath: 'music/9.mp3'},
        {imagePath: 'images/10.png', id:7, titleGR: 'Α.Ε.Κ.', title2: 'ΒΑΓΓΕΛΗΣ ΠΕΡΠΙΝΙΑΔΗΣ', title3: '', musicPath: 'music/10.mp3'},
        {imagePath: 'images/11.png', id:7, titleGR: 'ΥΜΝΟΣ ΤΗΣ Α.Ε.Κ.', title2: 'ΛΕΥΤΕΡΗΣ ΨΙΛΟΠΟΥΛΟΣ', title3: '', musicPath: 'music/11.mp3'},
        {imagePath: 'images/12.png', id:7, titleGR: 'ΟΤΑΝ ΦΟΡΑΣ ΤΑ ΚΙΤΡΙΝΑ', title2: 'ΦΡΕΙΔΕΡΙΚΟΣ', title3: '', musicPath: 'music/12.mp3'},
        {imagePath: 'images/13.png', id:7, titleGR: 'Α.Ε.Κ.', title2: 'ΣΩΤΟΣ ΣΚΟΤΙΔΑΣ - ΝΤΕΠΥ ΓΕΩΡΓΙΟΥ', title3: '', musicPath: 'music/13.mp3'},
        {imagePath: 'images/14.png', id:7, titleGR: 'ΦΙΛΑΔΕΛΦΙΩΤΙΣΣΑ', title2: 'Λ. ΨΙΛΟΠΟΘΛΟΣ', title3: '', musicPath: 'music/14.mp3'},
        {imagePath: 'images/15.png', id:7, titleGR: 'Α.Ε.Κ.', title2: 'ΣΠΥΡΟΣ ΜΑΥΡΟΦΤΑΣ', title3: '', musicPath: 'music/15.mp3'},
        {imagePath: 'images/16.png', id:7, titleGR: 'Α.Ε.Κ.', title2: 'ΓΙΩΡΓΟΣ ΤΑΣΟΥΛΗΣ - ΝΙΚΟΣ ΠΟΛΥΚΑΝΔΡΙΩΤΗΣ', title3: '', musicPath: 'music/16.mp3'},
        {imagePath: 'images/17.png', id:7, titleGR: 'ΥΜΝΟΣ ΣΤΗΝ Α.Ε.Κ.', title2: 'ΠΕΤΡΟΣ ΠΑΛΑΙΟΛΟΓΟΣ', title3: '', musicPath: 'music/17.mp3'},
        {imagePath: 'images/18.png', id:7, titleGR: 'ΥΜΝΟΣ ΣΤΗΝ Α.Ε.Κ.', title2: 'ΓΙΩΡΓΟΣ ΚΟΝΙΤΟΠΟΥΛΟΣ', title3: '', musicPath: 'music/18.mp3'},
        {imagePath: 'images/19.png', id:7, titleGR: 'Α.Ε.Κ.', title2: 'ΣΤΑΘΗΣ ΝΙΚΟΛΑΪΔΗΣ', title3: '', musicPath: 'music/19.mp3'},
        {imagePath: 'images/20.png', id:7, titleGR: 'Α.Ε.Κ. - ΣΛΑΒΙΑ', title2: 'ΤΕΛΙΚΟΣ ΚΥΠΕΛΛΟΥ ΚΥΠΕΛΛΟΥΧΩΝ', title3: 'ΕΥΡΩΠΗΣ ΜΠΑΣΚΕΤ 1968', musicPath: 'music/20.mp3'},
        {imagePath: 'images/21.png', id:7, titleGR: 'ΝΑΤΟΙ ΟΙ ΠΡΩΤΑΘΛΗΤΕΣ', title2: 'Λ.ΠΑΠΑΔΟΠΟΥΛΟΥ - Θ.ΠΟΛΥΚΑΝΔΡΙΩΤΗ', title3: '', musicPath: 'music/21.mp3'},
        {imagePath: 'images/22.png', id:7, titleGR: 'Ο ΥΜΝΟΣ ΤΗΣ Α.Ε.Κ.', title2: 'ΜΙΧΑΛΗΣ ΦΡΑΓΚΟΥΛΗΣ', title3: '', musicPath: 'music/22.mp3'},
        {imagePath: 'images/23.png', id:7, titleGR: 'Η ΑΕΚΑΡΑ', title2: 'ΡΟΜΠΕΡΤ ΓΟΥΙΛΙΑΜΣ', title3: '', musicPath: 'music/23.mp3'},
        {imagePath: 'images/24.png', id:7, titleGR: 'Ο ΥΜΝΟΣ ΤΗΣ Α.Ε.Κ.', title2: 'ΜΠΑΣΚΕΤ', title3: '', musicPath: 'music/24.mp3'},
        {imagePath: 'images/25.png', id:7, titleGR: 'ΜΙΑ ΑΓΑΠΗ ΕΧΩ ΣΤΗΝ ΚΑΡΔΙΑ', title2: 'ΦΟΙΒΟΣ - ΓΙΩΡΓΟΣ ΦΛΩΡΑΚΗΣ', title3: '', musicPath: 'music/25.mp3'},
        {imagePath: 'images/26.png', id:7, titleGR: 'ΕΝΑ ΤΡΑΓΟΥΔΙ ΓΙΑ ΤΗΝ Α.Ε.Κ.', title2: 'ΠΑΝΤΕΛΗΣ ΘΑΛΑΣΣΙΝΟΣ', title3: '', musicPath: 'music/26.mp3'},
        {imagePath: 'images/27.png', id:7, titleGR: 'ΠΡΟΣΦΥΓΙΑ', title2: 'ΨΕΥΔΟΚΡΑΤΟΡΑΣ', title3: '', musicPath: 'music/27.mp3'},
        {imagePath: 'images/28.png', id:7, titleGR: 'ΝΕΑ ΦΙΛΑΔΕΛΦΕΙΑ', title2: 'ΚΩΣΤΑΣ ΜΑΚΕΔΟΝΑΣ', title3: '', musicPath: 'music/28.mp3'},
        {imagePath: 'images/29.png', id:7, titleGR: 'ΑΕΚ', title2: 'ΙΔΕΑ ΕΧΩ ΕΣΕΝ ΚΑΙ ΤΗΝ ΑΓΙΑ ΣΟΦΙΑΝ', title3: 'ΤΣΙΦΤΕΛΙΔΗΣ ΓΙΩΡΓΟΣ', musicPath: 'music/29.mp3'},
        {imagePath: 'images/30.png', id:7, titleGR: 'ΤΙΓΡΗΣ ΑΕΚ', title2: 'ΔΗΜΗΤΡΗΣ ΚΑΡΑΣΑΒΒΙΔΗΣ', title3: '', musicPath: 'music/30.mp3'},
        {imagePath: 'images/31.png', id:7, titleGR: 'ΜΠΑΜΠΑ ΜΟΥ ΞΕΡΩ', title2: 'STAVENTO', title3: '', musicPath: 'music/31.mp3'},
    ];

export {vinylsList}